In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mlxtend
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [12]:
data = pd.read_excel('MyStudentsDB2.xlsx')

In [14]:
data.shape

(30, 12)

In [15]:
data.isnull().sum()

StuDentID                  0
Gender                     0
Age                        0
IsWorking                  0
CourseID                   0
TopicID                   30
Grade                      0
Nationality                0
TopicLanguage              0
StudentNativeLanguage      0
IsPresent                  0
Proffesor's mean score     0
dtype: int64

In [18]:
del data['TopicID']

In [19]:
data.head()

StuDentID Gender  Age IsWorking  CourseID  Grade Nationality TopicLanguage  \
0          1      M   19        No         1    100          HY            HY   
1          1      M   19        No         2    100          HY            HY   
2          1      M   19        No         3    100          HY            HY   
3          2      F   19  FullTime         1     81          HY            HY   
4          2      F   19  FullTime         2     75          HY            HY   

  StudentNativeLanguage  IsPresent  Proffesor's mean score  
0                    HY          1                      98  
1                    HY          1                     100  
2                    HY          1                      95  
3                    HY          0                      98  
4                    HY          1                     100

In [20]:
data.shape

(30, 11)

In [21]:
data.isnull().sum()

StuDentID                 0
Gender                    0
Age                       0
IsWorking                 0
CourseID                  0
Grade                     0
Nationality               0
TopicLanguage             0
StudentNativeLanguage     0
IsPresent                 0
Proffesor's mean score    0
dtype: int64

In [22]:
from numpy import array
from sklearn.preprocessing import LabelEncoder

label_enc = LabelEncoder()
data.Gender = label_enc.fit_transform(data.Gender)
data.head()

StuDentID  Gender  Age IsWorking  CourseID  Grade Nationality  \
0          1       1   19        No         1    100          HY   
1          1       1   19        No         2    100          HY   
2          1       1   19        No         3    100          HY   
3          2       0   19  FullTime         1     81          HY   
4          2       0   19  FullTime         2     75          HY   

  TopicLanguage StudentNativeLanguage  IsPresent  Proffesor's mean score  
0            HY                    HY          1                      98  
1            HY                    HY          1                     100  
2            HY                    HY          1                      95  
3            HY                    HY          0                      98  
4            HY                    HY          1                     100

In [23]:
label_enc = LabelEncoder()
data.Gender = label_enc.fit_transform(data.Gender)
data.IsWorking = label_enc.fit_transform(data.IsWorking)
data.Nationality = label_enc.fit_transform(data.Nationality)
data.TopicLanguage = label_enc.fit_transform(data.TopicLanguage)
data.StudentNativeLanguage = label_enc.fit_transform(data.StudentNativeLanguage)
data.head()

StuDentID  Gender  Age  IsWorking  CourseID  Grade  Nationality  \
0          1       1   19          2         1    100            1   
1          1       1   19          2         2    100            1   
2          1       1   19          2         3    100            1   
3          2       0   19          1         1     81            1   
4          2       0   19          1         2     75            1   

   TopicLanguage  StudentNativeLanguage  IsPresent  Proffesor's mean score  
0              0                      1          1                      98  
1              0                      1          1                     100  
2              0                      1          1                      95  
3              0                      1          0                      98  
4              0                      1          1                     100

### Applying Apriori

In [25]:
for i in data.columns:
    print('---------------------------')
    print(i)
    print('---------------------------')
    print(data[i].unique())

---------------------------
StuDentID
---------------------------
[ 1  2  3  4  5  6  7  8  9 10]
---------------------------
Gender
---------------------------
[1 0]
---------------------------
Age
---------------------------
[19 20 21]
---------------------------
IsWorking
---------------------------
[2 1 3 0]
---------------------------
CourseID
---------------------------
[1 2 3]
---------------------------
Grade
---------------------------
[100  81  75  61  40  60  80  50  90  95  55  71  62  52  41  77]
---------------------------
Nationality
---------------------------
[1 2 0]
---------------------------
TopicLanguage
---------------------------
[0]
---------------------------
StudentNativeLanguage
---------------------------
[1 0]
---------------------------
IsPresent
---------------------------
[1 0]
---------------------------
Proffesor's mean score
---------------------------
[ 98 100  95]


In [33]:
dfDummies = pd.get_dummies(data['Nationality'], prefix = 'Nationality')
pd.concat([data,dfDummies], axis=1)

In [39]:
dfDummies1 = pd.get_dummies(data["Proffesor's mean score"], prefix = "Proffesor's mean score")
dfDummies2 = pd.get_dummies(data['IsPresent'], prefix = 'IsPresent')
dfDummies3 = pd.get_dummies(data['StudentNativeLanguage'], prefix = 'StudentNativeLanguage')
dfDummies4 = pd.get_dummies(data['CourseID'], prefix = 'CourseID')
dfDummies5 = pd.get_dummies(data['IsWorking'], prefix = 'IsWorking')
dfDummies6 = pd.get_dummies(data['Age'], prefix = 'Age')
dfDummies7 = pd.get_dummies(data['Gender'], prefix = 'Gender')
dfDummies8 = pd.get_dummies(data['Grade'], prefix = 'Grade')

In [44]:
main = pd.concat([data,dfDummies,dfDummies1,dfDummies2,dfDummies3,dfDummies4,dfDummies5,dfDummies6,dfDummies7,dfDummies8], axis=1)

In [47]:
main.columns

Index(['Nationality_0', 'Nationality_1', 'Nationality_2',
       'Proffesor's mean score_95', 'Proffesor's mean score_98',
       'Proffesor's mean score_100', 'IsPresent_0', 'IsPresent_1',
       'StudentNativeLanguage_0', 'StudentNativeLanguage_1', 'CourseID_1',
       'CourseID_2', 'CourseID_3', 'IsWorking_0', 'IsWorking_1', 'IsWorking_2',
       'IsWorking_3', 'Age_19', 'Age_20', 'Age_21', 'Gender_0', 'Gender_1',
       'Grade_40', 'Grade_41', 'Grade_50', 'Grade_52', 'Grade_55', 'Grade_60',
       'Grade_61', 'Grade_62', 'Grade_71', 'Grade_75', 'Grade_77', 'Grade_80',
       'Grade_81', 'Grade_90', 'Grade_95', 'Grade_100'],
      dtype='object')

In [48]:
items = apriori(main, min_support=0.001, use_colnames=True)
items.head()

support                     itemsets
0  0.100000              (Nationality_0)
1  0.800000              (Nationality_1)
2  0.100000              (Nationality_2)
3  0.333333  (Proffesor's mean score_95)
4  0.333333  (Proffesor's mean score_98)

In [49]:
items.shape

(10630, 2)

In [53]:
rules = association_rules(items,metric='lift', min_threshold=1)

In [55]:
rules.head()

antecedents                   consequents  \
0              (Nationality_0)   (Proffesor's mean score_95)   
1  (Proffesor's mean score_95)               (Nationality_0)   
2              (Nationality_0)   (Proffesor's mean score_98)   
3  (Proffesor's mean score_98)               (Nationality_0)   
4              (Nationality_0)  (Proffesor's mean score_100)   

   antecedent support  consequent support   support  confidence  lift  \
0            0.100000            0.333333  0.033333    0.333333   1.0   
1            0.333333            0.100000  0.033333    0.100000   1.0   
2            0.100000            0.333333  0.033333    0.333333   1.0   
3            0.333333            0.100000  0.033333    0.100000   1.0   
4            0.100000            0.333333  0.033333    0.333333   1.0   

   leverage  conviction  
0       0.0         1.0  
1       0.0         1.0  
2       0.0         1.0  
3       0.0         1.0  
4       0.0         1.0

In [56]:
from sklearn.cluster import KMeans
import numpy as np

kmeans = KMeans(n_clusters=3, random_state=0).fit(rules)

TypeError: float() argument must be a string or a number, not 'frozenset'

In [61]:
type(rules)

pandas.core.frame.DataFrame

In [62]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.tranform(rules))

AttributeError: 'StandardScaler' object has no attribute 'tranform'